### ISSUE TITLE
error when using dbscan

### ISSUE THREAD

**Issue by wenyfan** [AI4EPS/GaMMA#27]
Hello,

I got the following errors when using dbscan. Any advice?

Thanks.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/wenyuanfan/opt/anaconda3/envs/ogamma/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/wenyuanfan/opt/anaconda3/envs/ogamma/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/wenyuanfan/opt/anaconda3/envs/ogamma/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/wenyuanfan/opt/anaconda3/envs/ogamma/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/wenyuanfan/opt/anaconda3/envs/ogamma/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/wenyuanfan/opt/anaconda3/envs/ogamma/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/wenyuanfan/opt/anaconda3/envs/ogamma/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Volumes/Durian/Projects/Gofar/G_5_GaMMa.py", line 108, in <module>
    catalogs, assignments = association(picks, stations, config, event_idx0, config["method"])
  File "/Users/wenyuanfan/opt/anaconda3/envs/ogamma/lib/python3.10/site-packages/gamma/utils.py", line 98, in association
    manager = mp.Manager()
  File "/Users/wenyuanfan/opt/anaconda3/envs/ogamma/lib/python3.10/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/Users/wenyuanfan/opt/anaconda3/envs/ogamma/lib/python3.10/multiprocessing/managers.py", line 562, in start
    self._process.start()
  File "/Users/wenyuanfan/opt/anaconda3/envs/ogamma/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/wenyuanfan/opt/anaconda3/envs/ogamma/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/Users/wenyuanfan/opt/anaconda3/envs/ogamma/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/wenyuanfan/opt/anaconda3/envs/ogamma/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/wenyuanfan/opt/anaconda3/envs/ogamma/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/wenyuanfan/opt/anaconda3/envs/ogamma/lib/python3.10/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/wenyuanfan/opt/anaconda3/envs/ogamma/lib/python3.10/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "/Volumes/Durian/Projects/Gofar/G_5_GaMMa.py", line 108, in <module>
    catalogs, assignments = association(picks, stations, config, event_idx0, config["method"])
  File "/Users/wenyuanfan/opt/anaconda3/envs/ogamma/lib/python3.10/site-packages/gamma/utils.py", line 98, in association
    manager = mp.Manager()
  File "/Users/wenyuanfan/opt/anaconda3/envs/ogamma/lib/python3.10/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/Users/wenyuanfan/opt/anaconda3/envs/ogamma/lib/python3.10/multiprocessing/managers.py", line 566, in start
    self._address = reader.recv()
  File "/Users/wenyuanfan/opt/anaconda3/envs/ogamma/lib/python3.10/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/Users/wenyuanfan/opt/anaconda3/envs/ogamma/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/Users/wenyuanfan/opt/anaconda3/envs/ogamma/lib/python3.10/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

**Comment by zhuwq0** [comment]
Hi Wenyuan, are you calling association inside multiprocessing? I have not seen this error before. The association fundtion already uses multiprocessing inside.

**Comment by wenyfan** [comment]
Hi Weiqiang,

Thanks for the speedy reply! 

> are you calling association inside multiprocessing? I have not seen this error before. 
No, my call is similar to the example code.

W.

**Comment by zhuwq0** [comment]
I just did a quick test. The example online is working fine on my side: https://ai4eps.github.io/GaMMA/example_phasenet/
That could be an issue of multiprocessing.

**Comment by wenyfan** [comment]
thanks! I agree. It seems like a python issue. I will try a few things and report back.

**Comment by wenyfan** [comment]
I think it's an issue with that computer. i used a different machine, and it worked fine. thanks, Weiqiang.

**Comment by shicks-seismo** [comment]
I had the same issue and I fixed it by encompassing the Gamma driving script within a if __name__ == '__main__': statement

**Comment by zhuwq0** [comment]
Hi Stephen, could you provide more details about the case?
